import { Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/common/NavBar";
import Footer from "@/components/common/Footer";
import { CartProvider } from "@/context/CartContext";
import Cart from "@/components/common/cart";
import { ToastContainer } from "react-toastify";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Greentech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <CartProvider>
          <div className="relative flex flex-col min-h-screen bg-white">
            <div className="sticky top-0 z-[100]">
              <NavBar />
            </div>
            <div className="flex-grow overflow-y-auto">
              <div>{children}</div>
              <Footer />
            </div>
            <Cart />
            <ToastContainer />
          </div>
        </CartProvider>
      </body>
    </html>
  );
}
