import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/common/NavBar";
import Footer from "@/components/common/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Greentech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative flex flex-col min-h-screen bg-[#F2F4F8] " >
        <div className="flex-grow overflow-y-auto">
          <NavBar />
          <div className="min-h-[calc(100vh-72px-64px)] lg:min-h-[calc(100vh-147px-64px)]">
            {children}
          </div>
          <Footer />
        </div>
        {/* <Cart /> */}
      </div>
      </body>
    </html>
  );
}
